/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ClothingItem, WeatherForecast } from './types';

export const COLORS = [
  { name: 'Charcoal Black', hex: '#1e1e1e' },
  { name: 'Off White', hex: '#fbfbfb' },
  { name: 'Navy Blue', hex: '#1e3a8a' },
  { name: 'Crimson Red', hex: '#991b1b' },
  { name: 'Classic Grey', hex: '#4b5563' },
  { name: 'Forest Green', hex: '#064e3b' },
  { name: 'Khaki Beige', hex: '#d97706' },
  { name: 'Soft Peach', hex: '#ffedd5' },
  { name: 'Sky Blue', hex: '#38bdf8' },
  { name: 'Lava Orange', hex: '#ea580c' },
  { name: 'Teal Green', hex: '#0f766e' },
  { name: 'Crimson Pink', hex: '#db2777' },
];

export const STYLES = ['Casual', 'Formal', 'Sporty', 'Business', 'Chic'] as const;

export const CATEGORIES = ['Top', 'Bottom', 'Outerwear', 'Footwear', 'Nightwear', 'Nightwear Top', 'Nightwear Bottom'] as const;

export const SEASONS = ['Summer', 'Winter', 'Fall/Spring', 'All-Year'] as const;

export const MATERIALS = [
  { name: 'Cotton (100%)', isQuickDry: false, category: 'organic' },
  { name: 'Linen', isQuickDry: true, category: 'organic' },
  { name: 'Polyester (Activewear)', isQuickDry: true, category: 'synthetic' },
  { name: 'Nylon (Performance)', isQuickDry: true, category: 'synthetic' },
  { name: 'Heavy Denim', isQuickDry: false, category: 'heavy' },
  { name: 'Chunky Wool', isQuickDry: false, category: 'heavy' },
  { name: 'Knitwear', isQuickDry: false, category: 'heavy' },
  { name: 'Leather', isQuickDry: false, category: 'heavy' },
  { name: 'Fleece (Polyester)', isQuickDry: true, category: 'synthetic' },
  { name: 'Suede', isQuickDry: false, category: 'heavy' },
  { name: 'Merino Wool (Light)', isQuickDry: true, category: 'organic' },
];

export const INITIAL_WARDROBE: ClothingItem[] = [
  // Tops (10 items)
  {
    id: 'top-1',
    name: 'Breezy Kurta',
    category: 'Top',
    style: 'Casual',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Off White',
    colorHex: '#fbfbfb',
    status: 'Clean',
    timesWorn: 2,
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-2',
    name: 'Active Polo',
    category: 'Top',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Polyester (Activewear)',
    isQuickDry: true,
    color: 'Sky Blue',
    colorHex: '#38bdf8',
    status: 'Clean',
    timesWorn: 5,
    imageUrl: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-3',
    name: 'Linen Shirt',
    category: 'Top',
    style: 'Chic',
    seasonalUse: 'Summer',
    material: 'Linen',
    isQuickDry: true,
    color: 'Soft Peach',
    colorHex: '#ffedd5',
    status: 'Clean',
    timesWorn: 1,
    imageUrl: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-4',
    name: 'Waterproof Cape',
    category: 'Top',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Nylon (Performance)',
    isQuickDry: true,
    color: 'Lava Orange',
    colorHex: '#ea580c',
    status: 'Clean',
    timesWorn: 3,
    imageUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-5',
    name: 'Oxford Shirt',
    category: 'Top',
    style: 'Business',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Navy Blue',
    colorHex: '#1e3a8a',
    status: 'Dirty',
    timesWorn: 4,
    imageUrl: 'https://images.unsplash.com/photo-1620012253295-c05cb3e65553?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-6',
    name: 'Lounge Tee',
    category: 'Top',
    style: 'Casual',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Classic Grey',
    colorHex: '#4b5563',
    status: 'Clean',
    timesWorn: 8,
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-7',
    name: 'Moisture Run Tee',
    category: 'Top',
    style: 'Sporty',
    seasonalUse: 'Summer',
    material: 'Polyester (Activewear)',
    isQuickDry: true,
    color: 'Forest Green',
    colorHex: '#064e3b',
    status: 'Clean',
    timesWorn: 9,
    imageUrl: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-8',
    name: 'Executive Shirt',
    category: 'Top',
    style: 'Formal',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Off White',
    colorHex: '#fbfbfb',
    status: 'Clean',
    timesWorn: 0,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-9',
    name: 'Mandarin Kurti',
    category: 'Top',
    style: 'Chic',
    seasonalUse: 'Summer',
    material: 'Linen',
    isQuickDry: true,
    color: 'Crimson Pink',
    colorHex: '#db2777',
    status: 'Clean',
    timesWorn: 2,
    imageUrl: 'https://images.unsplash.com/photo-1610030469668-93535c17b6b3?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'top-10',
    name: 'Indigo V-Neck',
    category: 'Top',
    style: 'Casual',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Sky Blue',
    colorHex: '#38bdf8',
    status: 'Dirty',
    timesWorn: 3,
    imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=400',
  },

  // Bottoms (6 items)
  {
    id: 'bot-1',
    name: 'Rain Cargo Pants',
    category: 'Bottom',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Nylon (Performance)',
    isQuickDry: true,
    color: 'Charcoal Black',
    colorHex: '#1e1e1e',
    status: 'Clean',
    timesWorn: 7,
    imageUrl: 'https://images.unsplash.com/photo-1517462964-21fdcec3f25b?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'bot-2',
    name: 'Rugged Jeans',
    category: 'Bottom',
    style: 'Casual',
    seasonalUse: 'All-Year',
    material: 'Heavy Denim',
    isQuickDry: false,
    color: 'Navy Blue',
    colorHex: '#1e3a8a',
    status: 'Clean',
    timesWorn: 12,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'bot-3',
    name: 'White Linen Pants',
    category: 'Bottom',
    style: 'Chic',
    seasonalUse: 'Summer',
    material: 'Linen',
    isQuickDry: true,
    color: 'Off White',
    colorHex: '#fbfbfb',
    status: 'Clean',
    timesWorn: 2,
    imageUrl: 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'bot-4',
    name: 'Dry Track Pants',
    category: 'Bottom',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Polyester (Activewear)',
    isQuickDry: true,
    color: 'Classic Grey',
    colorHex: '#4b5563',
    status: 'Clean',
    timesWorn: 6,
    imageUrl: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'bot-5',
    name: 'Chino Pants',
    category: 'Bottom',
    style: 'Business',
    seasonalUse: 'Fall/Spring',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Khaki Beige',
    colorHex: '#d97706',
    status: 'Clean',
    timesWorn: 4,
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'bot-6',
    name: 'Gym Shorts',
    category: 'Bottom',
    style: 'Sporty',
    seasonalUse: 'Summer',
    material: 'Polyester (Activewear)',
    isQuickDry: true,
    color: 'Charcoal Black',
    colorHex: '#1e1e1e',
    status: 'Dirty',
    timesWorn: 10,
    imageUrl: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=400',
  },

  // Outerwear (3 items)
  {
    id: 'out-1',
    name: 'Windbreaker Coat',
    category: 'Outerwear',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Nylon (Performance)',
    isQuickDry: true,
    color: 'Lava Orange',
    colorHex: '#ea580c',
    status: 'Clean',
    timesWorn: 5,
    imageUrl: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'out-2',
    name: 'Nehru Vest',
    category: 'Outerwear',
    style: 'Formal',
    seasonalUse: 'All-Year',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Teal Green',
    colorHex: '#0f766e',
    status: 'Clean',
    timesWorn: 1,
    imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'out-3',
    name: 'Fleece Jacket',
    category: 'Outerwear',
    style: 'Casual',
    seasonalUse: 'Winter',
    material: 'Fleece (Polyester)',
    isQuickDry: true,
    color: 'Charcoal Black',
    colorHex: '#1e1e1e',
    status: 'Clean',
    timesWorn: 2,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=400',
  },

  // Footwear (4 items)
  {
    id: 'foot-1',
    name: 'Waterproof Sandals',
    category: 'Footwear',
    style: 'Sporty',
    seasonalUse: 'All-Year',
    material: 'Nylon (Performance)',
    isQuickDry: true,
    color: 'Charcoal Black',
    colorHex: '#1e1e1e',
    status: 'Clean',
    timesWorn: 15,
    imageUrl: 'https://images.unsplash.com/photo-1621516762354-76f577cf3665?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'foot-2',
    name: 'Leather Oxfords',
    category: 'Footwear',
    style: 'Formal',
    seasonalUse: 'All-Year',
    material: 'Leather',
    isQuickDry: false,
    color: 'Charcoal Black',
    colorHex: '#1e1e1e',
    status: 'Clean',
    timesWorn: 3,
    imageUrl: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'foot-3',
    name: 'Walking Chappals',
    category: 'Footwear',
    style: 'Casual',
    seasonalUse: 'All-Year',
    material: 'Leather',
    isQuickDry: false,
    color: 'Khaki Beige',
    colorHex: '#d97706',
    status: 'Clean',
    timesWorn: 11,
    imageUrl: 'https://images.unsplash.com/photo-1605733513597-a8f8341084e6?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'foot-4',
    name: 'Slip-On Sneakers',
    category: 'Footwear',
    style: 'Chic',
    seasonalUse: 'Summer',
    material: 'Polyester (Activewear)',
    isQuickDry: true,
    color: 'Sky Blue',
    colorHex: '#38bdf8',
    status: 'Clean',
    timesWorn: 4,
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=400',
  },
  // Nightwear / Night Suits (3 premium sets of coordinates)
  {
    id: 'night-1',
    name: 'Cozy Fleece Pajama Pant Set',
    category: 'Nightwear Bottom',
    style: 'Casual',
    seasonalUse: 'Winter',
    material: 'Fleece (Polyester)',
    isQuickDry: true,
    color: 'Navy Blue',
    colorHex: '#1e3a8a',
    status: 'Clean',
    timesWorn: 2,
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'night-2',
    name: 'Classic Cotton Night Shirt',
    category: 'Nightwear Top',
    style: 'Casual',
    seasonalUse: 'Summer',
    material: 'Cotton (100%)',
    isQuickDry: false,
    color: 'Off White',
    colorHex: '#fbfbfb',
    status: 'Clean',
    timesWorn: 3,
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
  },
  {
    id: 'night-3',
    name: 'Silk Comfort Sleep Suit',
    category: 'Nightwear Top',
    style: 'Chic',
    seasonalUse: 'All-Year',
    material: 'Linen',
    isQuickDry: true,
    color: 'Soft Peach',
    colorHex: '#ffedd5',
    status: 'Clean',
    timesWorn: 1,
    imageUrl: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&q=80&w=400',
  },
];

export interface CityPreset {
  name: string;
  country: string;
  forecasts: WeatherForecast[];
}

export const CHUYE_KOLHAPUR_FORECAST: WeatherForecast[] = [
  { dayOffset: 0, dayName: 'Today (Monsoon)', temp: 24, condition: 'Rainy', humidity: 95, windSpeed: 25 },
  { dayOffset: 1, dayName: 'Tomorrow (Humid)', temp: 25, condition: 'Rainy', humidity: 90, windSpeed: 18 },
  { dayOffset: 2, dayName: 'Mon, Jun 22 (Overcast)', temp: 26, condition: 'Cloudy', humidity: 85, windSpeed: 14 },
  { dayOffset: 3, dayName: 'Tue, Jun 23 (Warm Rain)', temp: 27, condition: 'Rainy', humidity: 92, windSpeed: 20 },
];
